### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Victoria",
  "email": "victoria@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "erwin@test.com",
  "password": "password"
}

### auth test
GET http://localhost:3000/users.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NDgwNzE1Nzl9.pRjTcu4YnJ3u3EOTncJjpWmn8r6EmXcCKmZ0oz2tAb4